export default {
  'Russian Empire': 'Russia',
  'United Kingdom European Union membership referendum, 2016': 'Brexit',
  'United Kingdom withdrawal from the European Union': 'Brexit',
  'Production of Avengers: Infinity War': 'Avengers: Infinity War',
  'Avengers (comics)': 'Avengers: Infinity War',
  'Infinity War': 'Avengers: Infinity War',
  'Macron Stadium': 'Emmanuel Macron',
  'Macron': 'Emmanuel Macron',
  'Iran national football team': 'Iran',
  'Santa Fe High School (California)': 'Santa Fe High School (Texas)',
  'Santa Fe High School (New Mexico)': 'Santa Fe High School (Texas)',
  'Edmond Santa Fe High School': 'Santa Fe High School (Texas)',
  'Markle, Indiana': 'Meghan Markle',
  'Right to Censor': 'Meghan Markle',
  'The American Bride': 'Meghan Markle',
  'Harry S. Day': 'Prince Harry',
  'Kate Royal': 'Catherine, Duchess of Cambridge',
  'Good Morning Britain (2014 TV programme)': 'Good Morning Britain',
  'Macron (sportswear)': 'Emmanuel Macron',
  'Gaza War (2008–09)': 'Gaza Strip',
  'Welcome to the Family (song)': 'Wedding of Prince Harry and Meghan Markle',
  'H.O.T.S.': null,
  'The T.O. Show': null,
  'TBX21': null,
  '1993 Ramada Hotel drownings': null,
  'Freed.in': null,
  'The Pack (Buffy the Vampire Slayer)': null,
  "The Times They Are a-Changin' (song)": null,
  'Born to Kill (gang)': null,
  'Đinđuša': null,
  'Tołwin': null
}
