const CIRCULATIONS_ENTRY_ID = process.env.CIRCULATIONS_ENTRY_ID;
const CONTENTFUL_BASE_URL = process.env.CONTENTFUL_BASE_URL;
const CONTENTFUL_IMAGE_URL = process.env.CONTENTFUL_IMAGE_URL;
const CONTENT_DELIVERY_ACCESS_TOKEN = process.env.CONTENT_DELIVERY_ACCESS_TOKEN;
const RATINGS_ENTRY_ID = process.env.RATINGS_ENTRY_ID;
const SPACE_ID = process.env.SPACE_ID;
const PAGE_HOME_ENTRY_ID = process.env.PAGE_HOME_ENTRY_ID;
const PAGE_ABOUT_ENTRY_ID = process.env.PAGE_ABOUT_ENTRY_ID;
const PAGE_PORTFOLIO_ENTRY_ID = process.env.PAGE_PORTFOLIO_ENTRY_ID;

export {
  CIRCULATIONS_ENTRY_ID,
  CONTENTFUL_BASE_URL,
  CONTENTFUL_IMAGE_URL,
  CONTENT_DELIVERY_ACCESS_TOKEN,
  RATINGS_ENTRY_ID,
  SPACE_ID,
  PAGE_HOME_ENTRY_ID,
  PAGE_ABOUT_ENTRY_ID,
  PAGE_PORTFOLIO_ENTRY_ID
}
