const ALEXA_ENTRY_ID = process.env.ALEXA_ENTRY_ID;
const CIRCULATIONS_ENTRY_ID = process.env.CIRCULATIONS_ENTRY_ID;
const CONTENTFUL_BASE_URL = process.env.CONTENTFUL_BASE_URL;
const CONTENTFUL_IMAGE_URL = process.env.CONTENTFUL_IMAGE_URL;
const CONTENT_DELIVERY_ACCESS_TOKEN = process.env.CONTENT_DELIVERY_ACCESS_TOKEN;
const PRESS_COMPLAINTS_ID = process.env.PRESS_COMPLAINTS_ID;
const PRICES_ENTRY_ID = process.env.PRICES_ENTRY_ID;
const RATINGS_ENTRY_ID = process.env.RATINGS_ENTRY_ID;
const SPACE_ID = process.env.SPACE_ID;

export {
  ALEXA_ENTRY_ID,
  CIRCULATIONS_ENTRY_ID,
  CONTENTFUL_BASE_URL,
  CONTENTFUL_IMAGE_URL,
  CONTENT_DELIVERY_ACCESS_TOKEN,
  PRESS_COMPLAINTS_ID,
  PRICES_ENTRY_ID,
  RATINGS_ENTRY_ID,
  SPACE_ID
}
